| Created by Marc Mentat 2018.0.0 GA (64bit)
*prog_option compatibility:prog_version:ment2018
*prog_analysis_class structural
*prog_use_current_job on
*set_default_length_unit millimeter
*set_model_length_unit millimeter
|
*open_model "c:\users\akhta\onedrive - new mexico state university\mae_nmsu\2021\fall2021\me518_fea\project\mac-mentat\test2+\test2+.mud"
*fill_view
*model_orientation_iso3
*set_save_formatted off *save_as_model "..\test1+_Sweep\test1+_Sweep.mud" yes
*sweep_nodes
all_existing
# | End of List
*sweep_elements
*sweep_elements
all_existing
*save_model
*edit_job job1

*check_job
*update_job
*submit_job 1 *monitor_job
*save_model *quit yes
